# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sbd_cpp <- function(x, n1, n1_total, n2, n2_total) {
    .Call(`_Ball_sbd_cpp`, x, n1, n1_total, n2, n2_total)
}

