# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mq_cpp <- function(x, n1, n1_total, mq_res) {
    invisible(.Call(`_Ball_mq_cpp`, x, n1, n1_total, mq_res))
}

